### ISSUE TITLE
Bug of DMABuf on kernel 5.0-rc2 nightly

### ISSUE THREAD

**Issue by zhangchn** [01org/gvt-linux#66] opened 2019-01-18 07:28 UTC
On a DMABuf setting of qemu Windows 10 guest, sometimes a full-screen game causes guest window to show black screen with guest cursor.

Dmesg from host kernel:

```
[ 4181.438946] DMAR: DRHD: handling fault status reg 2
[ 4181.438960] DMAR: [DMA Write] Request device [00:02.0] fault addr a902000 [fault reason 23] Unknown
[ 4188.305313] [drm] GPU HANG: ecode 9:0:0x85dffffb, in qemu-system-x86 [2170], reason: hang on rcs0, action: reset
[ 4188.305314] [drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[ 4188.305314] [drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
[ 4188.305315] [drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[ 4188.305315] [drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
[ 4188.305316] [drm] GPU crash dump saved to /sys/class/drm/card0/error
[ 4188.306342] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
```

[error.txt](https://github.com/intel/gvt-linux/files/2771910/error.txt)

The host is ubuntu 18.04 with drm-nightly from https://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/2019-01-17/linux-image-unsigned-5.0.0-994-generic_5.0.0-994.201901171725_amd64.deb. A mdev of i915-GVTg_V5_4 was used.

The guest is 64-bit Windows 10.0.16299, with guest driver 25.20.100.6326 for HD Graphics 530.

**Comment by TerrenceXu** [comment] 2019-01-21 12:23
@zhangchn , We cannot reproduce this issue in our side with the deb packaged you provided.
Does it a regression? What the 3D APP you are running which occurred the GPU hang? How long running time you met this issue? GTK or Spicy you used?
Thanks!

**Comment by zhangchn** [comment] 2019-01-22 02:52
Hi, the game was StarCraft 2 and I cannot reproduce the bug either.

GTK was used. The bug occurred not long after Windows guest started.

QEMU was on origin/master commit 4b9f0b0.

**Comment by zhangchn** [comment] 2019-01-22 05:46
Reproduced again when starting the game/entering fullscreen mode:

```
Jan 22 13:32:16 user-ubuntu kernel: DMAR: DRHD: handling fault status reg 3
Jan 22 13:32:16 user-ubuntu kernel: DMAR: [DMA Write] Request device [00:02.0] fault addr 924000 [fault reason 23] Unknown
Jan 22 13:32:16 user-ubuntu kernel: DMAR: DRHD: handling fault status reg 3
Jan 22 13:32:16 user-ubuntu kernel: DMAR: [DMA Write] Request device [00:02.0] fault addr 9a9000 [fault reason 23] Unknown
Jan 22 13:32:16 user-ubuntu kernel: DMAR: DRHD: handling fault status reg 2
Jan 22 13:32:16 user-ubuntu kernel: DMAR: [DMA Write] Request device [00:02.0] fault addr 9ca000 [fault reason 23] Unknown
Jan 22 13:32:16 user-ubuntu kernel: DMAR: DRHD: handling fault status reg 2
Jan 22 13:32:24 user-ubuntu kernel: [drm] GPU HANG: ecode 9:0:0x85dffffb, in qemu-system-x86 [3471], reason: hang on rcs0, action: reset
Jan 22 13:32:24 user-ubuntu kernel: [drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
Jan 22 13:32:24 user-ubuntu kernel: [drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
Jan 22 13:32:24 user-ubuntu kernel: [drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
Jan 22 13:32:24 user-ubuntu kernel: [drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
Jan 22 13:32:24 user-ubuntu kernel: [drm] GPU crash dump saved to /sys/class/drm/card0/error
Jan 22 13:32:24 user-ubuntu kernel: i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
```

[card_error.txt](https://github.com/intel/gvt-linux/files/2781437/card_error.txt)

**Comment by TerrenceXu** [comment] 2019-01-22 07:22
@zhangchn , I saw some DMAR error from your log, can you add "intel_iommu=igfx_off" in your host grub and try again?

**Comment by zhangchn** [comment] 2019-01-23 05:22
@TerrenceXu After adding intel_iommu=igfx_off, the no more blackout or crash occurred, so far. And h.264 playback seems to work better than without igfx_off.

**Comment by TerrenceXu** [comment] 2019-01-23 09:09
@zhangchn , we sugguest to keep intel_iommu with igfx_off to avoid some DMAR related issues, hope it can meet your requirement.

**Comment by adam314315** [comment] 2019-05-02 11:49
Hello, 

I suceeded to set up gvt with  Linux Kernel 5 / Ubuntu 18.04 / gvt-stable 4.17 / Intel graphics card (26.20.100.6709) but I got a black screen while trying to start the instance. Please find below the Vnc and dsmeg screenshot. Any suggestion where I should start to try to fix?

![gvt-log](https://user-images.githubusercontent.com/35598037/57073231-fd95e500-6ccf-11e9-8324-b097439aaed2.jpg)
![gvt-vnc](https://user-images.githubusercontent.com/35598037/57073232-fe2e7b80-6ccf-11e9-9fa5-11138c68426c.jpg)

**Comment by adam314315** [comment] 2019-05-03 05:49
Finally succeeded to fix the issue by doing the setup on a i7 machine. I guess the E5 I was using was an old version with some bugs with the gvt library.

**Comment by xzhan34** [comment] 2020-10-21 03:14
closed this issue per the history.

**Closed as completed** 2020-10-21 03:35 UTC
