### ISSUE TITLE
Blacked out fonts in Windows GVT-g guests

### ISSUE THREAD

**Issue by chriscjs** [01org/gvt-linux#63] opened 2018-12-05 01:36 UTC
In Windows 10/7 guests I get what looks like the following

![screenshot_20181204_182951](https://user-images.githubusercontent.com/5388452/49484164-4ade5b00-f7f3-11e8-8b6e-c8b323637ca3.png)

The issue does not occur in Linux guests.  The guests have the latest Intel drivers installed.  I also downloaded and built the latest "gvt-staging" git kernel and that does not help.  It does not occur in bare-metal Win10, which I dual-boot with Arch linux.

Host has skylake 6700hq with hd 530 running Arch linux, kernel 4.19.5.

**Comment by hyuan3** [comment] 2018-12-05 01:38
We've noticed it and it's under investigation. Thanks.

**Comment by TerrenceXu** [comment] 2018-12-05 13:12
@chriscjs , I guess it due to there are two version qemu in your host, maybe "qemu-kvm" and "qemu-system-x86_64".
If you only keep one qemu version in your host, this issue will be gone.
Can you confirm it?

**Comment by chriscjs** [comment] 2018-12-05 15:34
There is only "qemu-system-x86_64" on my system and the issue still occurs.  Arch linux does not provide a "qemu-kvm".

**Comment by TerrenceXu** [comment] 2018-12-06 01:48
What is you qemu version?
Can you provide me "qemu-system-x86_64 --version" and "qemu-img --version" data?

**Comment by chriscjs** [comment] 2018-12-06 03:36
QEMU emulator version 3.0.0
qemu-img version 3.0.0
This issue was also present in the previous qemu 2.12.

**Comment by worron** [comment] 2018-12-09 23:33
By the way, on my system the issue can be reproduced only while host compositor (compton) active. Turning off compositor before qemu launch prevent the problem with 100% guaranty.

**Comment by franklee1973** [comment] 2018-12-17 02:50
Hi Worron, 
   What is the host compositor refer to? I have a centos 7 with GVT-g install, I have the same problem, but I have not find any program names compton.

Thanks!

**Comment by worron** [comment] 2018-12-17 14:32
I'm referring to [compositing window manager](https://wiki.archlinux.org/index.php/Xorg#Composite). Not sure how it works exactly, may be GPU activity should be minimizated on qemu launch. I only  have noticed that disabling compton prevent blacked out fonts issue in my case and thought it may give some ideas.

**Comment by TerrenceXu** [comment] 2018-12-20 12:57
@chriscjs @franklee1973 @worron Does it a regression? Can you reproduce it with our gvt-stable-4.17 kernel?

**Comment by TerrenceXu** [comment] 2018-12-26 07:16
We also confirm this issue is related to host compositor. 
Host desktop with xwayland, can reproduce this issue.
Host desktop with x11, cannot reproduce this issue.
Host without desktop, cannot reproduce this issue.

**Comment by subjectdenied** [comment] 2018-12-28 23:10
i see this too: kabylake, hd620, arch, kernel 4.20, gnome 3.30 with X11. i'm using qemu with gtk, gl=on

meanwhile i did a reboot after having installed intel-media-kit on arch, this maybe accidently fixed the issue?

**Comment by TerrenceXu** [comment] 2019-01-03 08:56
@subjectdenied , this issue only happened while host compositor active, we are under internal debugging, thanks!

**Comment by TerrenceXu** [comment] 2019-03-12 08:55
This issue can be fixed by below patch.
1e8b15a1988e drm/i915/gvt: Add in context mmio 0x20D8 to gen9 mmio list

**Closed as completed** 2020-10-14 06:33 UTC
