### ISSUE TITLE
get 1920x1080 resolution in GVT-g scenario

### ISSUE THREAD

**Issue by rugubara** [01org/gvt-linux#132] opened 2019-12-25 07:49 UTC
I run my VMs on a laptop with 16:9 screen. I want to run them fullscreen sometimes and 1920x1200 resolution leaves annoying black bars at the top and the bottom when I try to use 1920x1080 resolution. 
When I use 1920x1200, I have grey bars at the right and left sides. 
I would like to fit the VM screen nicely into my 16:9 but I couldn't figure out how to achieve this.
![1920x1080](https://user-images.githubusercontent.com/9335047/71437753-04141980-2704-11ea-95f6-9dfd5b0d992e.png)
![1920x1200](https://user-images.githubusercontent.com/9335047/71437759-070f0a00-2704-11ea-8eb8-99fd413289f0.png)

**Comment by tinywrkb** [comment] 2019-12-26 16:20
The usual `xres`, `yres` should work if your CPU is supported for EDID, you're running kernel 5.1 or newer and QEMU 4.0 or newer , see `qemu-system-x86_64 -device vfio-pci,help`. Last time I checked Broadwell is not supported.  
And you can always use CRU, the custom resolution utility, to change the supported resolutions of the virtual display.

**Comment by rugubara** [comment] 2020-01-17 17:08
I have Coffee-lake CPU - Intel(R) Core(TM) i7-8850H. When I tried to set xres and yres the guest failed to start:
`2020-01-17T16:28:43.227300Z qemu-system-x86_64: -device vfio-pci,id=hostdev0,sysfsdev=/sys/bus/mdev/devices/ac4c1b78-ca88-4d43-a1b5-402d377a8d2b,display=on,bus=pci.5,addr=0x0: vfio ac4c1b78-ca88-4d43-a1b5-402d377a8d2b: xres and yres properties need edid support`

**Comment by rugubara** [comment] 2020-01-17 19:13
I was able to change the resolution to 1920x1080 by using CRU. Is there a way to script it to run at every boot?

**Comment by tinywrkb** [comment] 2020-01-17 19:24
IIRC with CRU you can permanently remove unwanted resolutions so you only need to run it once. I never needed to make this change more than once on any of my W10 installations.

There's [a patch to enable EDID for all platform](https://lists.freedesktop.org/archives/intel-gvt-dev/2019-December/006185.html).

**Comment by ChristophSchmidpeter** [comment] 2020-01-18 19:12
@tinywrkb Thanks, the patch you have pointed out made it work for me with 1920x1080.

**Comment by ChristophSchmidpeter** [comment] 2020-01-18 19:15
@TerrenceXu The [EDID patch](https://lists.freedesktop.org/archives/intel-gvt-dev/2019-December/006185.html), which @tinywrkb mentioned, seems to have not been applied to the gvt-linux repository yet. Is the gvt-linux repository not up-to-date with the patches from the mailing list, or how is the workflow there? Will the EDID patch be merged into gvt-linux?

**Comment by hyuan3** [comment] 2020-01-19 02:54
Yes, the patch will be merged into gvt-linux after test on more platforms.

**Comment by TerrenceXu** [comment] 2020-01-19 08:00
Thanks all for the notification, the  [EDID patch](https://lists.freedesktop.org/archives/intel-gvt-dev/2019-December/006185.html) can resolve this problem.

**Comment by ChristophSchmidpeter** [comment] 2020-01-19 11:26
@hyan3 @TerrenceXu Thank you for the info. Good to hear it will be merged when ready to do so.

**Comment by rugubara** [comment] 2020-01-20 19:09
> Thanks all for the notification, the [EDID patch](https://lists.freedesktop.org/archives/intel-gvt-dev/2019-December/006185.html) can resolve this problem.

Maybe I missed smth... I applied the patch on top of 5.4.13 kernel (on the host) and I still get "xres and yres properties need edid support" starting the qemu/kvm machine.

**Comment by shunlir** [comment] 2020-03-05 01:21
Does client mouse work with spice-gtk/gl + dmabuf? it doesn't work for me. (EDID patch works for me: kernel 5.4 + Coffee lake)

**Comment by rugubara** [comment] 2020-03-05 12:21
@shunlir , I also hit this bug. I work it around by keeping the mouse cursor in the window until the guest driver initializes the display.
If the cursor is outside or the guest window is closed, I get the cursor disappearing as soon as it enters the guest window.

**Comment by shunlir** [comment] 2020-03-06 15:02
@rugubara , perhaps I'm experiencing a different issue, cursor in guest is always visible even I mouse client mouse outside spice-gtk window. Absolute mouse position is working, but the problem is guest doesn't send cursor_set message to spice client, so server-side cursor rendering is used.

**Closed as completed** 2020-10-22 05:14 UTC
