### ISSUE TITLE
IGD OpRegion feature: No such device

### ISSUE THREAD

**Issue by DocMAX** [01org/gvt-linux#19] opened 2018-02-12 20:48 UTC
vfio error: 59c57b6c-13ee-4055-846e-e4d3dc55d389: does not support requested IGD OpRegion feature: No such device

What does this error mean? How can i fix this?

**Comment by FanFansfan** [comment] 2018-07-31 14:36
encounter same issue.
platform info: i5 5200u, linux 4.14.52-gentoo, qemu 2.12.0.
kernel config CONFIG_KVMGT, CONFIG_GVT, CONFIG_VFIO_MDEV, CONFIG_VFIO_MDEV_DEVICE = y.

### new:
update kernel to 4.17.10 and it works with qemu 2.12.0

**Comment by kourindouhime** [comment] 2018-12-08 07:31
I'm running 4.19.7 and qemu 3.0.0 (-dirty), and it says

qemu-system-x86_64: -device vfio-pci,host=00:02.0,bus=pci.0,addr=0x2,x-igd-opregion=on: vfio error: 0000:00:02.0: does not support requested IGD OpRegion feature: No such device

**Comment by kourindouhime** [comment] 2018-12-09 05:01
Built 4.20.0-rc4+ from https://github.com/intel/gvt-linux.git, still same error

**Comment by kourindouhime** [comment] 2018-12-09 05:44
```
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e899340) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e899370) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e8993a0) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e8993d0) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e899400) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e899430) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e899460) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e899490) = 0
ioctl(23, VFIO_DEVICE_GET_REGION_INFO, 0x557f4e899490) = -1 EINVAL (Invalid argument)
brk(0x557f4e8db000)                     = 0x557f4e8db000
brk(0x557f4e907000)                     = 0x557f4e907000
brk(0x557f4e931000)                     = 0x557f4e931000
brk(0x557f4e95c000)                     = 0x557f4e95c000
brk(0x557f4e986000)                     = 0x557f4e986000
fstat(2, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 3), ...}) = 0
write(2, "qemu-system-x86_64: -device vfio"..., 178qemu-system-x86_64: -device vfio-pci,host=00:02.0,bus=pci.0,addr=0x2,x-igd-opregion=on: vfio error: 0000:00:02.0: does not support requested IGD OpRegion feature: No such device
) = 178
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by TerrenceXu** [comment] 2018-12-10 09:07
@kourindouhime `qemu-system-x86_64: -device vfio-pci,host=00:02.0,bus=pci.0,addr=0x2,x-igd-opregion=on` is GVT-d boot up command, you must unbind 00:02.0 first, you can follow below Wiki:
https://github.com/intel/gvt-linux/wiki/GVTd_Setup_Guide#51-preparing-a-graphic-card-device-for-passthrough-for-gvt-d-kvm

For GVT-g, you can follow https://github.com/intel/gvt-linux/wiki/GVTg_Setup_Guide#5-basic-usage, I have tested with kernel 4.19.7 + qemu 3.0.0, it is working without IGD OpRegion problem.

**Comment by kourindouhime** [comment] 2018-12-12 13:41
Thanks for reply, but I already unbind. It works without x-igd-opregion=on, it doesn't work with "x-igd-opregion=on".

**Comment by TerrenceXu** [comment] 2018-12-13 15:20
@kourindouhime , can you provide the full create VM command, since we cannot reproduce your issue for both GVT-g and GVT-d.

**Comment by kourindouhime** [comment] 2018-12-14 19:04
@TerrenceXu okay, I've managed to DO IT. I don't know why, but it's mandatory to set IGD as a boot GPU. Also don't use latest grub, efifb does something to GPU when booting with it. Efifb didn't happen to me on ubuntu 17.10 and Debian Stretch. On 18.04's grub-efi boot param video=efifb:off had no impact for me.

If you boot with other GPU than IGD, you won't be able to use opregion vfio parameter. Otherwise it works for both UPT and legacy.

**Comment by kourindouhime** [comment] 2018-12-14 19:05
great job! I also would like to confirm VGA output working. Though I have to add rombar=0 to the vfio-pci string now. I don't see seabios loading screen, but if you're lucky enough to boot guest OS with intel GPU driver, external display will show your desktop.

**Comment by kourindouhime** [comment] 2019-01-21 22:55
I've performed a setup from scratch later and "rombar=0" didn't have impact, and I had to specify romfile=anything, so it loads nothing. My device line looks like this now:
```
-device vfio-pci,host=0:02.0,addr=0x02,rombar=0,x-igd-opregion=on,x-vga=on,romfile=undefined
```
The purpose of this is to get rid of "IGD device 0000:00:02.0 has no ROM, legacy mode disabled". If this error occurs, with UPT mode you won't be able to output anything from physical gpu ports, so you need legacy. Also you have to boot into OS of your choice blindly! And it should have preinstalled latest intel graphics driver, so it fixes gpu on initialization. I hope it helps!

**Comment by TerrenceXu** [comment] 2020-09-16 12:57
Close it and focus on the latest kernel.

**Closed as completed by TerrenceXu** 2020-09-16 12:57 UTC
