### ISSUE TITLE
Low framerate with dma-buf output

### ISSUE THREAD

**Issue by Ordspilleren** [01org/gvt-linux#35] opened 2018-04-26 17:56 UTC
Hello,

I have dma-buf working with GVT-g on kernel 4.16 and QEMU 2.12. The framerate of the framebuffer output is very low however (seems to be around ~20 fps). I've run the Heaven benchmark in the VM, and that seems to perform about as expected, so it's only the dma-buf output that's slow. Does anyone else experience this?

I'm using Libvirt with local SPICE and OpenGL. Also tried different Intel drivers in the VM, no difference.

**Comment by Saren-Arterius** [comment] 2018-05-05 05:57
Same here. What can be changed to improve the framerate?

**Comment by bangom** [comment] 2018-08-05 20:41
Same here, refresh rate of whole "dmabuffed" display is really bad via Spice or GTK. OpenGL / DirectX apps FPS seems OK. Tested on Windows 10 Enterprise 1803 Guest with latest 24.20.100.6194 Intel drivers, custom compiled Qemu 2.12.1 and 4.18.0 kernel from http://kernel.ubuntu.com/~kernel-ppa/mainline/drm-intel-nightly/2018-08-03/ (using it because of another bug)... all on Ubuntu 18.04. Any help please?

**Comment by bangom** [comment] 2018-08-11 16:00
When using spicy client conneced to local dmabuff VM try turning off spice protocol compression, refreshrate seems normal OK then! 

qemu-system-x86_64 ... -spice disable-ticketing,port=5910,image-compression=off,streaming-video=off,playback-compression=off,jpeg-wan-compression=never,zlib-glz-wan-compression=never

**Comment by worron** [comment] 2018-08-15 15:47
@bangom
Do you managed to get real 60fps with spice? I tried dma-buf with spice no compression and gtk but fps always about 20-30 (visually) despite inner counters in games and benchmarks shows much more.

**Comment by bangom** [comment] 2018-08-15 17:16
@worron, well maybe not 60fps... more like 30fps. But huge step when comparing spice compression on (~5fps) and off (~30fps). Hope there will be fix soon so we can use GVT in OpenGL game scenarios on a Windows host.

**Comment by worron** [comment] 2018-08-15 18:16
OK, thanks for clarification. Current state of dma-buf (~30fps) is pretty good but still not perfect. I'm just following the issue hoping for improvements.

**Comment by Saren-Arterius** [comment] 2018-08-18 18:52
Tried gnif/looking-glass on a win10, can achieve 60fps in testufo, when under some kind of GPU load the fps drops to 10ish, not better than dma-buf for this case.

**Comment by Saren-Arterius** [comment] 2018-08-18 18:54
When under heavy load (3dmark) dma-buf stutters really bad, it could freeze for 0.5s before showing next frame, while the 3dmark runs at 12-15fp

Using virt-manager, gpu is uhd620

**Comment by zhangchn** [comment] 2018-11-13 06:13
Hi, DMA-Buf via GTK is throttled to 33Hz by default fresh rate of GTK display.

Change definition of macro `GUI_REFRESH_INTERVAL_DEFAULT` in `include/ui/console.h` to 16 or 17 (milliseconds) and then rebuild qemu.

I have filed a bug at launchpad.net for qemu.

**Comment by Saren-Arterius** [comment] 2018-11-13 06:15
Thanks! I wonder why is the throttle 33hz, instead of 60hz or client display refresh rate.

**Comment by Saren-Arterius** [comment] 2018-11-13 06:15
Oops it seems this is not the place to ask.

在 2018年11月13日週二 14:14，Saren Arterius <ykmran@gmail.com> 寫道：

**Comment by zhangchn** [comment] 2018-11-13 06:54
> Thanks! I wonder why is the throttle 33hz, instead of 60hz or client display refresh rate.

Tracking down the commit history, the interval of 30 milliseconds dates back to 10+ years ago when VGA emulation was first introduced.

https://github.com/qemu/qemu/commit/313aa567104a63fbe84d6ec2eeff5b5c81cb3524

**Comment by worron** [comment] 2018-11-16 23:12
@zhangchn, thank you! Finally can enjoy fair 60fps in gvt accelerated VM.

Also I'm asking all concerned to vote the bug at launchpad.

**Comment by CuriousTommy** [comment] 2018-12-15 14:33
Here is a link to the launchpad report: https://bugs.launchpad.net/qemu/+bug/1802915

**Comment by CuriousTommy** [comment] 2019-02-14 04:03
@zhangchn I was wondering, is there a formula that determines what the `GUI_REFRESH_INTERVAL` is (How did you know to use 16 or 17 milliseconds to get 60hz)?

Someone could make a function that sets the right value based on the monitor that is currently connected.

**Comment by mafrasi2** [comment] 2019-03-08 04:03
@CuriousTommy That's just the inverse of 60hz: 1/60hz=0.016666s.

**Comment by Saren-Arterius** [comment] 2019-03-25 13:51
https://gist.github.com/Saren-Arterius/b31df23d5c359523f1ef430d27b0e834
Here is my 2 revisions of qemu patch attempt. They should fail miserably.

**Comment by ChristophSchmidpeter** [comment] 2020-03-05 10:24
> Hi, DMA-Buf via GTK is throttled to 33Hz by default fresh rate of GTK display.
> 
> Change definition of macro `GUI_REFRESH_INTERVAL_DEFAULT` in `include/ui/console.h` to 16 or 17 (milliseconds) and then rebuild qemu.
> 
> I have filed a bug at launchpad.net for qemu.

I have set GUI_REFRESH_INTERVAL_DEFAULT to 17 as described and then recompiled quemu, but the framerate seems to bee still as low as before. Does anyone have the same issue, or know why that might be?

**Comment by ChristophSchmidpeter** [comment] 2020-03-05 10:26
@TerrenceXu : Is there any plan to implement adaptive fps in the near future? I think that would be very important for gvt to be more practical/useful.

**Comment by SanderVocke** [comment] 2020-04-24 14:20
@TitusLabienus: I just upgraded from qemu 4.2.0 (the Arch repository package) to qemu 5.0.0 rc4 (the Arch AUR qemu-git package), which I have modified with GUI_REFRESH_INTERVAL_DEFAULT=17.

I noticed a definite improvement in smoothness. In the guest I opened a YouTube video with a 30fps/60fps side-by-side comparison and could clearly see that the 60fps was way smoother.

However, the mouse cursor is still very choppy and still "feels" like 30fps, which is surprising to me.

Does anyone know if there is something special going on with the mouse in qemu with Intel GVT-g?

**Comment by j1warren** [comment] 2020-06-21 15:15
Relevant [patch](https://git.qemu.org/?p=qemu.git;a=commitdiff;h=c4c00922cc948bb5e879bfae60764eba1f8745f3)

**Comment by metenn** [comment] 2020-06-22 00:07
> I have set GUI_REFRESH_INTERVAL_DEFAULT to 17 as described and then recompiled quemu, but the framerate seems to bee still as low as before. Does anyone have the same issue, or know why that might be?

Are you 100% sure that Qemu is using the newly compiled binaries? I was stupid enough to just run `make install` thinking that'd do it, but virt-manager was running qemu from /usr/bin, and make install only moved it to /usr/local/bin.

> Relevant [patch](https://git.qemu.org/?p=qemu.git;a=commitdiff;h=c4c00922cc948bb5e879bfae60764eba1f8745f3)

Was this not merged to the master branch already?
https://github.com/qemu/qemu/blob/master/ui/gtk.c#L2038
Relevant commits
https://github.com/qemu/qemu/commit/c4c00922cc948bb5e879bfae60764eba1f8745f3
https://github.com/qemu/qemu/commit/31ab416d7dcb73a72efd59b9031f96a3944fbbe4
https://github.com/qemu/qemu/commit/7f4d96f960dcba6778d2c2dde2d653c9446115e4

      
     
Am I the only one still struggling with a laggy/stuttery/"30FPS" mouse in the libvirt viewer, even after applying the "60FPS" patch?

**Comment by ghost** [comment] 2020-06-23 14:32
@matthiasmeten Nope you're not the only one. I'm stuck with Low FPS mouse cursor with 60FPS virtualized desktop. Any fix for this?

**Comment by metenn** [comment] 2020-06-23 19:53
Passing through a mouse, for instance, makes it smooth, but now I notice some general visual latency. Could be my video mode though

**Comment by ghost** [comment] 2020-06-24 09:26
I'm working this out on my laptop and I have passed through my touchpad to guest using evdev tutorial I found online. The cursor lag seems to disappear when I remove spice channel from my vm but the rendered resolution is wrong (though the guest reports 1920x1080, the display window has vertical bars on the side). If I add spice channel back, the mouse cursor starts lagging. Is this something related to spice buffers?

Edit: Fixed it by adding xres and yres [Refer](https://github.com/intel/gvt-linux/issues/132)

**Comment by nikp123** [comment] 2020-08-17 13:06
@metenn @UmashankarTriforce Am the dev who send the initial patch here. I've tracked down the bug, but the repair requires input from the guys maintaining that piece of code, I've already tried to email kraxel, but I got no reply.

The issue is that the check ALWAYS fails due to an oversight in the "execution procedure". At the time when ```gd_refresh_rate_millihz``` gets executed, neither s->window or vc->window can be used. This is because vc->window has not been initialized, while s->window is hidden, thus failing the check ```if(win)```.

So this means that the code is effectively (so called 'ghost code') that never gets executed.

When does the function run exactly? Only during window initialization.

**Comment by nikp123** [comment] 2020-08-17 13:07
it's annoying how such a dumb bug can last for so long due to over-engineered (IMO) design

**Comment by nikp123** [comment] 2020-08-17 13:12
I've got two, somewhat sane solutions, but obviously I need input, since I'm not too familiar with the QEMU codebase.
 1) Move the check somewhere else, like a window resize (if possible)
 2) Yank that window open for just a brief moment so the pointer is valid (kinda hacky and will need some justification for it's existence)

**Comment by nikp123** [comment] 2020-08-17 13:13
And no, removing the check doesn't work, since it will always default to monitor 0, which might not be the one you're using fxp.

**Comment by nikp123** [comment] 2020-08-17 13:32
@kraxel Hate to bother you, but can you give your input on this, I would greatly appreciate it. Thanks for your work, by the way.

**Comment by nikp123** [comment] 2020-08-17 17:30
Nevermind, one of the maintainers got to me and wrote a patch. Should be merged pretty quick.

**Comment by nikp123** [comment] 2020-08-17 19:12
https://lists.nongnu.org/archive/html/qemu-devel/2020-08/msg03718.html

**Closed as completed** 2020-09-16 13:19 UTC

**Comment by altmnt** [comment] 2020-09-21 19:15
I am experiencing latency on kernel 5.8.10 and qemu built from master branch of the official repo (5.1.50). After setting GUI_REFRESH_INTERVAL_DEFAULT it's all smooth but I fee a general lag about 100-200ms (maybe due to the optimus graphics). 	
If i set -display gtk,gl=on,**show-cursor=on** I can see two cursors and guest cursor is delayed by aforementioned interval. 
Otherwise performance is good and smooth.
I have also added i915.enable_fbc=0 to the grub but it didnt help

**Comment by ManiaciaChao** [comment] 2022-02-21 06:04
> I am experiencing latency on kernel 5.8.10 and qemu built from master branch of the official repo (5.1.50). After setting GUI_REFRESH_INTERVAL_DEFAULT it's all smooth but I fee a general lag about 100-200ms (maybe due to the optimus graphics). If i set -display gtk,gl=on,**show-cursor=on** I can see two cursors and guest cursor is delayed by aforementioned interval. Otherwise performance is good and smooth. I have also added i915.enable_fbc=0 to the grub but it didnt help

The guest cursor moves smoothly when using a pass-through/USB-redirected mouse. It seems like the cursor movement is somehow delayed from host to guest.
