### ISSUE TITLE
Non-supported pixel format "0xc"

### ISSUE THREAD

**Issue by ghost** [01org/gvt-linux#56] opened 2018-11-05 06:28 UTC
YouTube video playback on Microsoft Edge in Windows 10 guest causes freeze and prints dmesg error

    [ 1328.099198] gvt: vgpu 1: Non-supported pixel format (0xc)

Google Chrome can play YouTube video just fine.

**Comment by TerrenceXu** [comment] 2018-12-04 09:38
Hi @RtzLi , we cannot reproduce the guest freeze issue with Microsoft Edge.
But we reproduced several "gvt: vgpu 1: Non-supported pixel format (0xc)" error log one time during long time media file played in local media player.
What Windows GFX driver you used?
Can you provide the detail youtube address?

**Comment by webi123** [comment] 2018-12-11 10:28
Hi @TerrenceXu,

I've discovered the same issue using the following setup:

- CPU: Core i7 7700T
- host kernel: 4.19.0 - arguments
  - i915.enable_gvt=1 kvm.ignore_msrs=1 intel_iommu=on drm.debug=0
- guest os: Windows 10 Pro 1803 Build 17134.1
- guest GFX driver: Intel HD Graphics 630 25.20.100.6444
- QEMU: 3.0.0 (IGD Assignment: Legacy mode) - arguments:
  - -machine type=q35,accel=kvm,kernel_irqchip=on
  - -cpu host
  - -bios /usr/bin/bios.bin
  - -drive if=virtio,file=<path>/Windows10.qcow2,aio=native,cache.direct=on,l2-cache-size=8M
  - -smp 4,cores=4
  - -m 4G
  - -enable-kvm
  - -object rng-random,id=rng0,filename=/dev/urandom
  - -device virtio-rng-pci,rng=rng0
  - -monitor stdio
  - -serial tcp::4444,server
  - -device qemu-xhci,id=xhci
  - -device usb-tablet
  - -M graphics=off
  - -vga none
  - -display gtk,gl=on
  - -device vfio-pci,sysfsdev=/sys/bus/pci/devices/0000:00:02.0/97d40b8a-f89d-11e8-a95f-4ff9be8f1398,display=on,x-igd-opregion=on
  - vGPU with WUXGA resolution (i915-GVTg_V5_4)

I see different kinds of behavior:

- during YouTube video playback in Microsoft Edge (42.17134.1.0) the whole VM screen freezes (no mouse pointer movement, no reaction on keyboard press) while host kernel continuously traces the 'gvt: vgpu 1: Non-supported pixel format (0xc)' line and QEMU monitor shows '(qemu) qemu-system-x86_64: eglCreateImageKHR failed' (-> corresponds to issue #59 )
- each video (also advertisement) shows the issue
- YouTube video works only if in background (while start menu is opened) - closing the start menu blanks the video frame (and also shows the trace)
- in round about 50% of all boot cases the initial login picture is visible and after login the VM desktop is not painted at all; when pressing windows button the start menu is painted but nothing else, neither a window nor the taskbar

**Comment by daramos** [comment] 2019-03-15 04:37
Looks like this is NV12 pixel format related. That pixel format is currently not implemented in fb_decoder.c

**Comment by marcel-apf** [comment] 2019-04-06 15:46
Hi @daramos,
I saw this patch that aims to fix the issue:
   https://patchwork.kernel.org/patch/10059031/
and an older version:
   https://patchwork.kernel.org/patch/9843913/
Does anybody know why it wasn't merged?

**Comment by HouQiming** [comment] 2019-05-08 09:02
I fixed this issue to the point that the whole VM screen still freezes, but the video plays correctly on the frozen screen. After finishing the video, one can minimize the Edge window with a hotkey, which unfreezes the VM screen.

The reason the whole screen freezes is that once a video loads in edge, the guest driver reports the decoded video surface as the primary display, and host can no longer get a pointer to the real primary display surface. The 'eglCreateImageKHR failed thing is caused by the GVT driver mis-reporting surface dimensions, but the format itself is supported. Finally, QEMU needs a new set of shaders plus `gl=es` to display those images correctly.

The fixes are committed to my [github](https://github.com/HouQiming/gvt-linux) [repos](https://github.com/HouQiming/qemu) and interested parties can check them there.

**Comment by marcel-apf** [comment] 2019-05-12 12:07
Hi @HouQiming,
Thanks for sharing your findings, I think issue https://github.com/intel/gvt-linux/issues/59 is related to the same problem and they also solved it partially.

**Comment by HouQiming** [comment] 2019-05-12 12:36
Thanks for the pointer! I made a reply there. When I have time I can try to
combine their patch with my QEMU fix.

**Comment by marcel-apf** [comment] 2019-05-31 15:48
Hi,
Using latest QEMU (master branch from official repository), Linux kernel 5.1 stable and a VM with Windows v.1903 (May. 2019) and latest IGD driver solves the issue completely for me.

**Comment by dingzhc** [comment] 2020-10-21 07:01
@TerrenceXu should be closed.

**Closed as completed** 2020-10-21 15:14 UTC
