### ISSUE TITLE
"rcs0 reset request timed out"

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [01org/gvt-linux#137] opened 2020-01-07 17:54 UTC
The whole system hung and in the dmesg log I got the following errors:

> [ 3030.908380] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
> [ 3030.909135] [drm:gen8_reset_engines [i915]] *ERROR* rcs0 reset request timed out: {request: 00000001, RESET_CTL: 00000001}
> [...]
> [ 3100.880718] i915 0000:00:02.0: GPU recovery timed out, cancelling all in-flight rendering

Possibly related to #136

Files
------------------
[dmesg.txt](https://github.com/intel/gvt-linux/files/4031799/dmesg.txt)
[Win10Uefi.txt](https://github.com/intel/gvt-linux/files/4031800/Win10Uefi.txt)

Client System:
------------------
OS: Windows 10
Firmware: Uefi

Host System:
------------------
System: Thinkpad P72
OS: Arch Linux
CPU: Coffee Lake (i7-8750H)
GPU: Optimus system with UHD Graphics 630 + Quadro P600
Driver: xf86-video-intel (1:2.99.917+899+gf66d3954-1) nvidia-dkms (440.44-8)
Kernel: vanilla (5.4.7.arch1-1)

**Comment by Saren-Arterius** [comment] 2020-01-13 03:39
Hi, I think this problem is from upstream and still not fixed as of 5.4.10: https://linuxreviews.org/Kernel_5.4.1_And_5.3.14_Are_Released_Making_Linux_Users_With_Intel_iGPUs_Finally_Able_To_Use_5.3-Series_Kernels

**Comment by ChristophSchmidpeter** [comment] 2020-01-13 13:39
@Saren-Arterius Thank you for the info! It might very well be that issue, as I remember to run more stable when I tried some time ago.

Edit: The article says that the issue was fixed with 5.4.1, and I run 5.4.7 already. So maybe the issue hasn't been properly fixed still.

**Comment by TerrenceXu** [comment] 2020-01-16 06:18
Can you try the latest 5.5 kernel? it is much more stable than 5.4.

**Comment by ChristophSchmidpeter** [comment] 2020-01-16 09:10
@TerrenceXu Ok, I will test it when 5.5 will have been released. Or do you mean the latest release candidate?

**Comment by 0x808** [comment] 2020-02-08 17:22
I have the same trouble. It should be fixed as soon as possible.

**Comment by Azkali** [comment] 2020-02-13 04:22
I also had this issue with linux5.4.18-1, after installing linux5.5.2-1 fixed it, no error show up in log.

CPU/iGPU : Intel m3 7y30 - Intel HD 615
Host: 5.5.2-1-Manjaro GNOME
Guest: Latest Windows 10
Drivers : Latest Intel gfx driver

**Comment by spaceone** [comment] 2020-09-01 14:31
same here?:
```
Sep  1 15:13:17 kernel: [210695.673093] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
Sep  1 15:13:17 kernel: [210695.673869] [drm:gen8_reset_engines [i915]] *ERROR* rcs0 reset request timed out: {request: 00000001, RESET_CTL: 00000001}
Sep  1 15:13:17 kernel: [210695.674116] i915 0000:00:02.0: Resetting chip for hang on rcs0
Sep  1 15:13:17 kernel: [210695.675895] [drm:gen8_reset_engines [i915]] *ERROR* rcs0 reset request timed out: {request: 00000001, RESET_CTL: 00000001}
Sep  1 15:13:17 kernel: [210695.676671] [drm:gen8_reset_engines [i915]] *ERROR* rcs0 reset request timed out: {request: 00000001, RESET_CTL: 00000001}
Sep  1 15:13:21 kernel: [210698.872035] Asynchronous wait on fence i915:sway[1666]:9b789c timed out (hint:intel_atomic_commit_ready+0x0/0x4c [i915])
Sep  1 15:13:25 kernel: [210703.676017] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
Sep  1 15:13:27 kernel: [210705.688020] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
Sep  1 15:13:35 kernel: [210713.687945] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
Sep  1 15:13:37 kernel: [210715.671949] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
```
Debian GNU/Linux 10 \n \l
Linux xxx 5.4.0-0.bpo.4-amd64 #1 SMP Debian 5.4.19-1~bpo10+1 (2020-03-09) x86_64 GNU/Linux

**Comment by coxuintel** [comment] 2020-09-17 04:57
Can't reproduce the issue on CFL.
Host 1, Ubuntu kernel: replace default kernel to tags/v5.4.65 on git.kernel.org.
Host 2, Arch kernel: core/linux-lts 5.4.65-1.
Windows 10 version & driver: OS: 10.0.18362, iGFX: 27.20.100.8476

What's your iGFX driver version?

**Comment by TerrenceXu** [comment] 2020-10-12 11:31
Close it first since we cannot reproduce it with the latest Windows GFX driver, anyone can reproduce it can reopen.

**Closed as completed by TerrenceXu** 2020-10-12 11:31 UTC
